/**
 * Seed FAQ corpus. ~20 entries per locale. Edit freely; running the
 * /admin/seed-faq endpoint re-uploads everything (it's idempotent on id).
 */
export interface FaqEntry {
  id: string                 // stable id, used as Vectorize vector id
  lang: "pt" | "en"
  question: string
  answer: string
}

export const FAQ_CORPUS: FaqEntry[] = [
  // ---- Portuguese ----
  { id: "pt-address",
    lang: "pt",
    question: "Onde fica a clínica?",
    answer: "A clínica EQUAL Care fica em Lisboa. Avisa no chat se quiseres a morada exacta — confirmamos antes da consulta." },
  { id: "pt-hours",
    lang: "pt",
    question: "Quais são os horários de funcionamento?",
    answer: "A clínica está aberta de segunda a sexta, das 09:00 às 19:00. Aos sábados, das 09:00 às 13:00." },
  { id: "pt-specialties",
    lang: "pt",
    question: "Que especialidades oferecem?",
    answer: "Trabalhamos em Medicina Geral, Nutrição, Psicologia e outras especialidades. Quando marcas uma consulta, vejo o que está disponível." },
  { id: "pt-insurance",
    lang: "pt",
    question: "Que seguros aceitam?",
    answer: "Aceitamos os principais seguros de saúde portugueses. Diz-me qual o teu e confirmo no momento da consulta." },
  { id: "pt-payment",
    lang: "pt",
    question: "Como é que pago a consulta?",
    answer: "Podes pagar no balcão por MB Way, multibanco ou cartão. Se tens seguro, fazemos a comparticipação directamente." },
  { id: "pt-parking",
    lang: "pt",
    question: "Há estacionamento?",
    answer: "Sim, há estacionamento perto da clínica. Não temos parque próprio, mas há lugares na rua e parques pagos a poucos minutos a pé." },
  { id: "pt-prep-first",
    lang: "pt",
    question: "Como devo preparar a primeira consulta?",
    answer: "Traz documento de identificação, cartão de seguro (se aplicável) e qualquer informação clínica relevante (exames, medicação actual, alergias)." },
  { id: "pt-companion",
    lang: "pt",
    question: "Posso levar acompanhante?",
    answer: "Sim, podes levar uma pessoa de acompanhamento. Para crianças, é obrigatória a presença de um adulto responsável." },
  { id: "pt-tele",
    lang: "pt",
    question: "Fazem teleconsultas?",
    answer: "Sim, algumas especialidades oferecem teleconsulta. No momento da marcação verás se essa opção está disponível para a especialidade que escolheres." },
  { id: "pt-cancel",
    lang: "pt",
    question: "Como cancelo uma consulta?",
    answer: "Podes cancelar aqui mesmo no chat — diz-me \"cancelar\" ou usa o botão As minhas consultas. Pedimos cancelamento com pelo menos 24h de antecedência." },
  { id: "pt-reschedule",
    lang: "pt",
    question: "Como mudo uma consulta?",
    answer: "Diz \"reagendar\" no chat e mostro-te as tuas consultas. Escolhes a que queres mudar e ofereço novos horários." },
  { id: "pt-late",
    lang: "pt",
    question: "Posso chegar atrasado?",
    answer: "Recomendamos chegar 10 minutos antes. Atrasos superiores a 15 minutos podem implicar reagendamento, dependendo da agenda do profissional." },
  { id: "pt-prescription",
    lang: "pt",
    question: "Como recebo a receita médica?",
    answer: "Após a consulta, o profissional emite a receita electrónica. Podes acedê-la na app EQUAL Care ou recebê-la directamente no farmácia indicada." },
  { id: "pt-results",
    lang: "pt",
    question: "Onde vejo os resultados de exames?",
    answer: "Os resultados ficam disponíveis na app EQUAL Care. Quando estiverem prontos, recebes uma notificação." },
  { id: "pt-pediatric",
    lang: "pt",
    question: "Atendem crianças?",
    answer: "Sim, atendemos crianças nas especialidades aplicáveis. Podes marcar consulta para um menor — durante a consulta tem de estar acompanhado por um adulto responsável." },
  { id: "pt-emergency",
    lang: "pt",
    question: "E se tiver uma urgência?",
    answer: "Se for uma urgência médica (dor no peito intensa, dispneia súbita, hemorragia, sintomas neurológicos), liga 112 ou dirige-te ao serviço de urgência mais próximo. A clínica não substitui cuidados de urgência." },
  { id: "pt-language",
    lang: "pt",
    question: "Falam inglês?",
    answer: "Vários dos nossos profissionais comunicam em inglês. Se precisas, avisa antes da consulta para confirmarmos a disponibilidade." },
  { id: "pt-data",
    lang: "pt",
    question: "Os meus dados estão seguros?",
    answer: "Sim. Cumprimos o RGPD e mantemos os teus dados de saúde com encriptação e acesso restrito ao profissional que te acompanha." },
  { id: "pt-contact",
    lang: "pt",
    question: "Como contacto a clínica?",
    answer: "Para questões administrativas, contacta a recepção pelo email da clínica. Para marcações e gestão de consultas, fala comigo aqui." },
  { id: "pt-newpatient",
    lang: "pt",
    question: "Sou novo paciente, como começo?",
    answer: "Cria a tua conta na app EQUAL Care e completa o registo. Depois podes voltar aqui e marco a tua primeira consulta." },

  // ---- English ----
  { id: "en-address",
    lang: "en",
    question: "Where is the clinic?",
    answer: "EQUAL Care clinic is in Lisbon. Ping me in chat if you'd like the exact address — we confirm it ahead of every appointment." },
  { id: "en-hours",
    lang: "en",
    question: "What are your opening hours?",
    answer: "The clinic is open Monday–Friday 09:00–19:00 and Saturday 09:00–13:00." },
  { id: "en-specialties",
    lang: "en",
    question: "What specialties do you offer?",
    answer: "We cover General Medicine, Nutrition, Psychology and other specialties. When you book, I'll show what's currently available." },
  { id: "en-insurance",
    lang: "en",
    question: "Which insurance do you accept?",
    answer: "We accept the main Portuguese health insurers. Tell me which one and we'll confirm at the appointment." },
  { id: "en-payment",
    lang: "en",
    question: "How do I pay?",
    answer: "You can pay at reception with MB Way, debit card or cash. If you have insurance, we handle the reimbursement directly." },
  { id: "en-parking",
    lang: "en",
    question: "Is there parking nearby?",
    answer: "Yes — we don't have our own car park but there are street spaces and paid car parks within a short walk." },
  { id: "en-prep-first",
    lang: "en",
    question: "How should I prepare for my first appointment?",
    answer: "Bring an ID document, your insurance card (if applicable), and any relevant clinical information (test results, current medication, allergies)." },
  { id: "en-companion",
    lang: "en",
    question: "Can I bring someone with me?",
    answer: "Yes, you can bring one companion. For minors, an accompanying responsible adult is required." },
  { id: "en-tele",
    lang: "en",
    question: "Do you offer telehealth?",
    answer: "Yes, some specialties offer telehealth. You'll see this option at booking time when it's available for the specialty you pick." },
  { id: "en-cancel",
    lang: "en",
    question: "How do I cancel an appointment?",
    answer: "You can cancel right here — say \"cancel\" or use the My appointments button. Please cancel at least 24h ahead." },
  { id: "en-reschedule",
    lang: "en",
    question: "How do I reschedule?",
    answer: "Say \"reschedule\" and I'll show you your bookings. Pick the one to change and I'll offer new slots." },
  { id: "en-late",
    lang: "en",
    question: "What if I'm running late?",
    answer: "We recommend arriving 10 minutes early. Delays over 15 minutes may need rescheduling depending on the practitioner's schedule." },
  { id: "en-prescription",
    lang: "en",
    question: "How do I get my prescription?",
    answer: "After the appointment, the practitioner issues an e-prescription. It's visible in the EQUAL Care app or sent directly to the pharmacy you choose." },
  { id: "en-results",
    lang: "en",
    question: "Where do I see test results?",
    answer: "Results become available in the EQUAL Care app. You'll get a notification when they're ready." },
  { id: "en-pediatric",
    lang: "en",
    question: "Do you see children?",
    answer: "Yes, in the relevant specialties. You can book on behalf of a minor — they must be accompanied by a responsible adult during the appointment." },
  { id: "en-emergency",
    lang: "en",
    question: "What about emergencies?",
    answer: "For a medical emergency (severe chest pain, sudden shortness of breath, bleeding, neurological symptoms), call 112 or go to the nearest A&E. The clinic does not replace emergency care." },
  { id: "en-language",
    lang: "en",
    question: "Do you speak Portuguese?",
    answer: "Yes — and most practitioners also speak English. Let us know your preference when booking." },
  { id: "en-data",
    lang: "en",
    question: "Is my data safe?",
    answer: "Yes. We comply with GDPR and keep your health data encrypted with restricted access — only the practitioner caring for you can read it." },
  { id: "en-contact",
    lang: "en",
    question: "How do I contact the clinic?",
    answer: "For admin questions, email the front desk. For bookings and changes, just talk to me here." },
  { id: "en-newpatient",
    lang: "en",
    question: "I'm a new patient — how do I start?",
    answer: "Create your account in the EQUAL Care app and finish the registration there. Then come back and I'll book your first appointment." }
]
